require_relative "../lib/wiki_scraper.rb"
require_relative "../lib/wiki_scraper/cli.rb"
require_relative "../lib/wiki_scraper/scraper.rb"
require_relative "../lib/wiki_scraper/version.rb"
require "nokogiri"
require "httparty"